version: '3'
volumes:
  postgres_data:
    driver: local
services:
  nginx:
    image: nginx:latest
    container_name: idealy-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './app:/var/www/html'
      - './config/nginx:/etc/nginx/conf.d'
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - "8080:8080"
    depends_on:
      - postgres
