version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    build:
      dockerfile: Dockerfile
    command:
      - start
    volumes:
      - ./conf:/opt/keycloak/conf
      - ./providers:/opt/keycloak/providers
    environment:
      KC_DB: mysql
      KC_HOSTNAME: auth.host.uk.com
      KC_DB_URL_HOST: 10.0.0.3
      DB_DATABASE: auth
      KC_DB_USERNAME: keycloak
      DB_SCHEMA: public
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
      - "8443:8443"
