version: '3'
services:
  keycloak:
    build:
      dockerfile: Dockerfile
    command:
      - start
      - --optimized
    volumes:
      - ./conf:/opt/keycloak/conf
      - ./providers:/opt/keycloak/providers
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8443:8443"
