version: '3'
services:
  keycloak:
    build:
      dockerfile: Dockerfile
    command:
      - start
      - --features=docker,token-exchange,account-api,account2,web-authn,impersonation,js-adapter,authorization,admin2,recovery-codes,scripts,update-email,par
    volumes:
      - ./conf:/opt/keycloak/conf
      - ./providers:/opt/keycloak/providers
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8443:8443"
